package sorting.util;

public class InputDataType {
		public int option;
		public int[] array;
	
		/*
		 * for didactic purpose only
		 * also a little lazy right now
		 * 
		 * but i know, getters and setter!!
		 * TODO if it would be for didactic purposes lazy would not be an option!!!
		 * this could easily be just a inner class where you use it!
		 * getter and setter can be generated by eclipse: right click > source > generate getter and setters
		 */
	
}
